version: '3'

tasks:
  up:
    desc: Builds end to end an AKS environment
    cmds:
    - terraform -chdir=./infrastructure workspace new {{.REGION}} || true
    - terraform -chdir=./infrastructure workspace select {{.REGION}}
    - terraform -chdir=./infrastructure init
    - terraform -chdir=./infrastructure apply -auto-approve -var "region={{.REGION}}"
    - task: creds
    - task: provider-config
    vars:
      REGION: '{{default "southcentralus" .CLI_ARGS}}'
    
  creds:
    desc: Grab AKS credentials 
    cmds:
    - az aks get-credentials -g {{.RG}} -n {{.CP_AKS}} --overwrite-existing
    - kubelogin convert-kubeconfig -l azurecli
    vars:
      RG: 
        sh: terraform -chdir=./infrastructure output -raw AKS_RESOURCE_GROUP
      CP_AKS: 
        sh: terraform -chdir=./infrastructure output -raw crossplane_AKS_CLUSTER_NAME

  provider-config:
    desc: Update upbound azure provider configuration
    cmds:
    - export AKS_TENANT_ID={{.AKS_TENANT_ID}} ;
      export AKS_SUBSCRIPTION_ID={{.AKS_SUBSCRIPTION_ID}} ;
      export UMI_CLIENT_ID={{.UMI_CLIENT_ID}} ;
      envsubst < ./cluster-configs/management/upbound-providers-config/azure-config.tmpl > ./cluster-configs/management/upbound-providers-config/azure-config.yaml
    - git add ./cluster-configs/management/upbound-providers-config/azure-config.yaml
    - git commit -m "Updated Azure configuration"
    - git push
    vars:
      AKS_TENANT_ID: 
        sh: terraform -chdir=./infrastructure output -raw AKS_TENANT_ID
      AKS_SUBSCRIPTION_ID: 
        sh: terraform -chdir=./infrastructure output -raw AKS_SUBSCRIPTION_ID
      UMI_CLIENT_ID: 
        sh: terraform -chdir=./infrastructure output -raw UMI_CLIENT_ID

  down:
    desc: Destroys all Azure resources and cleans up terraform
    cmds:
    - cd infrastructure ;
      rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info
    - az group delete -n {{.RG}} --yes || true
    vars:
      RG: 
        sh: terraform -chdir=./infrastructure output -raw AKS_RESOURCE_GROUP
