version: '3'

#env:
  
tasks:
  environment:
    desc: Creates Azure infrastructure and deploys application code
    cmds:
    - terraform -chdir=./infrastructure init
    - terraform -chdir=./infrastructure apply -auto-approve
    #- task: creds
 
  #creds:
  #  desc: Gets credential file for newly created AKS cluster
  #  cmds:
  #  - az aks get-credentials -g {{.RG}} -n {{.AKS}} --overwrite-existing
  #  - kubelogin convert-kubeconfig -l azurecli
  #  vars:
  #    RG: 
  #      sh: terraform -chdir=./infrastructure output -raw APP_RESOURCE_GROUP
  #    AKS: 
  #      sh: terraform -chdir=./infrastructure output -raw AKS_CLUSTER_NAME

  #deploy:
  #  desc: Deploys application code via helm
  #  cmds:
  #  - helm upgrade -i app .
  #  vars:

  clean:
    desc: Destroys Azure infrastructure and cleans up terraform state files
    cmds:
    - cd infrastructure ;
      rm -rf .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info
    - az group delete -n {{.RG}} --yes || true
    vars:
      RG: 
        sh: terraform -chdir=./infrastructure output -raw APP_RESOURCE_GROUP