apiVersion: v1
kind: Namespace
metadata:
  name: upbound-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: upbound-stable
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.upbound.io/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: upbound
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: upbound-system
  chart:
    spec:
      chart: universal-crossplane
      version: 'v1.16.0-up.1'
      sourceRef:
        kind: HelmRepository
        name: upbound-stable
        namespace: flux-system
      interval: 1m

  
  
