---
apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: bjdapp01-demo-rg
  labels:
    meta.upbound.io/rg-name: bjdapp01-demo-rg
    meta.upbound.io/type: azure-resource-group
    bjdazure.tech/app-name: bjdapp01
spec:
  providerConfigRef:
    name: azure
  forProvider:
    location: SouthCentral US
---
apiVersion: operationalinsights.azure.upbound.io/v1beta1
kind: Workspace
metadata:
  name: bjdlogs002
  labels:
    bjdazure.tech/law-name: bjdlogs002
    bjdazure.tech/app-name: bjdapp01
spec:
  providerConfigRef:
    name: azure
  forProvider:
    location: SouthCentral US
    resourceGroupNameSelector:
      matchLabels:
        meta.upbound.io/rg-name: bjdapp01-demo-rg
    retentionInDays: 30
    sku: PerGB2018
---
apiVersion: containerapp.azure.upbound.io/v1beta1
kind: Environment
metadata:
  name: bjdcae02
  labels:
    bjdazure.tech/app-name: bjdapp01
    bjdazure.tech/cae-name: bjdcae02
spec:
  providerConfigRef:
    name: azure
  forProvider:
    location: SouthCentral US
    logAnalyticsWorkspaceIdSelector:
      matchLabels:
        bjdazure.tech/law-name: bjdlogs002
    resourceGroupNameSelector:
      matchLabels:
        meta.upbound.io/rg-name: bjdapp01-demo-rg
---
apiVersion: containerapp.azure.upbound.io/v1beta1
kind: ContainerApp
metadata:
  name: bjdapp01
  labels:
    bjdazure.tech/app-name: bjdapp01
spec:
  providerConfigRef:
    name: azure
  forProvider:
    containerAppEnvironmentIdSelector:
      matchLabels:
        bjdazure.tech/cae-name: bjdcae02
    resourceGroupNameSelector:
      matchLabels:
        meta.upbound.io/rg-name: bjdapp01-demo-rg
    revisionMode: Single
    template:
      - container:
          - cpu: 0.25
            image: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
            memory: 0.5Gi
            name: bjdapp01containerapp