---
apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: bjdapp01-demo-rg
  labels:
    meta.upbound.io/rg-name: bjdapp01-demo-rg
    meta.upbound.io/type: azure-resource-group
    bjdazure.tech/app-name: bjdapp01
spec:
  providerConfigRef:
    name: azure
  forProvider:
    location: SouthCentral US
---
apiVersion: containerapp.azure.upbound.io/v1beta1
kind: Environment
metadata:
  name: bjdcae01
  labels:
    bjdazure.tech/app-name: bjdapp01
    bjdazure.tech/cae-name: bjdcae01
spec:
  forProvider:
    location: SouthCentral US
    resourceGroupNameSelector:
      matchLabels:
        meta.upbound.io/rg-name: bjdapp01
---
apiVersion: containerapp.azure.upbound.io/v1beta1
kind: ContainerApp
metadata:
  name: bjdapp01
  labels:
    bjdazure.tech/app-name: bjdapp01
spec:
  forProvider:
    containerAppEnvironmentIdSelector:
      matchLabels:
        bjdazure.tech/cae-name: bjdcae01
    resourceGroupNameSelector:
      matchLabels:
        meta.upbound.io/rg-name: bjdapp01-demo-rg
    revisionMode: Single
    template:
      - container:
          - cpu: 0.25
            image: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
            memory: 0.5Gi
            name: bjdapp01containerapp