apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xcluster-dev
  labels:
    crossplane.io/xrd: xaksclusters.containers.bjdazure.tech
    provider: azure
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: containers.bjdazure.tech/v1alpha1
    kind: XAKSCluster
  resources:
  - name: azure-resource-group
    base:
      apiVersion: azure.upbound.io/v1beta1
      kind: ResourceGroup
      metadata:
        annotations:
          meta.upbound.io/api-id: upbound/v1beta1
        labels:
          meta.upbound.io/rg-name: crossplane-demo-rg
          meta.upbound.io/type: azure-resource-group
        name: crossplane-demo-rg
      spec:
        providerConfigRef:
          name: azure
    patches:
    - fromFieldPath: spec.parameters.location
      toFieldPath: spec.forProvider.location
      transforms:
        - type: map
          map:
            southcentralus: South Central US
            northcentralus: North Central US
  - name: azure-vnet
    base:
      apiVersion: network.azure.upbound.io/v1beta1
      kind: VirtualNetwork
      metadata:
        annotations:
          meta.upbound.io/api-id: upbound/v1beta1
        labels:
          meta.upbound.io/rg-name: crossplane-demo-rg
          meta.upbound.io/vnet-name: crossplane-vnet
          meta.upbound.io/type: azure-virtual-network
        name: crossplane-vnet
      spec:
        providerConfigRef:
          name: azure
        forProvider:
          addressSpace:
            - 10.183.0.0/16
          resourceGroupNameSelector:
            matchLabels:
              meta.upbound.io/rg-name: crossplane-demo-rg
              meta.upbound.io/type: azure-resource-group
    patches:
    - fromFieldPath: spec.parameters.location
      toFieldPath: spec.forProvider.location
      transforms:
        - type: map
          map:
            southcentralus: South Central US
            northcentralus: North Central US
  - name: azure-subnet-private-endpoints
    base:
      apiVersion: network.azure.upbound.io/v1beta1
      kind: Subnet
      metadata:
        name: private-endpoints
        labels:
          meta.upbound.io/type: azure-virtual-subnet
          meta.upbound.io/subnet-for: private-endpoints
      spec:
        providerConfigRef:
          name: azure
        forProvider:
          addressPrefixes:
            - 10.183.1.0/24
          resourceGroupNameSelector:
            matchLabels:
              meta.upbound.io/rg-name: crossplane-demo-rg
              meta.upbound.io/type: azure-resource-group
          virtualNetworkNameSelector:
            matchLabels:
              meta.upbound.io/vnet-name: crossplane-vnet
              meta.upbound.io/type: azure-virtual-network
  - name: azure-subnet-kubernetes-nodes
    base:
      apiVersion: network.azure.upbound.io/v1beta1
      kind: Subnet
      metadata:
        name: kubernetes-nodes
        labels:
          meta.upbound.io/type: azure-virtual-subnet
          meta.upbound.io/subnet-for: akscluster-nodes
      spec:
        providerConfigRef:
          name: azure
        forProvider:
          addressPrefixes:
            - 10.183.3.0/24
          resourceGroupNameSelector:
            matchLabels:
              meta.upbound.io/rg-name: crossplane-demo-rg
              meta.upbound.io/type: azure-resource-group
          virtualNetworkNameSelector:
            matchLabels:
              meta.upbound.io/vnet-name: crossplane-vnet
              meta.upbound.io/type: azure-virtual-network
  - name: azure-subnet-kubernetes-api
    base:
      apiVersion: network.azure.upbound.io/v1beta1
      kind: Subnet
      metadata:
        name: kubernetes-api-server
        labels:
          meta.upbound.io/type: azure-virtual-subnet
          meta.upbound.io/subnet-for: akscluster-api-server
      spec:
        providerConfigRef:
          name: azure
        forProvider:
          addressPrefixes:
            - 10.183.2.0/24
          resourceGroupNameSelector:
            matchLabels:
              meta.upbound.io/rg-name: crossplane-demo-rg
              meta.upbound.io/type: azure-resource-group
          virtualNetworkNameSelector:
            matchLabels:
              meta.upbound.io/vnet-name: crossplane-vnet
              meta.upbound.io/type: azure-virtual-network
  - name: azure-aks-cluster
    base:
      apiVersion: containerservice.azure.upbound.io/v1beta1
      kind: KubernetesCluster
      metadata:
        name: aks
        labels:
          meta.upbound.io/rg-name: crossplane-demo-rg
          meta.upbound.io/type: azure-kubernetes-service
      spec:
        providerConfigRef:
          name: azure
        forProvider:
          automaticChannelUpgrade: "patch"
          oidcIssuerEnabled: true
          workloadIdentityEnabled: true
          skuTier: Standard 
          runCommandEnabled: true
          localAccountDisabled: true
          azureActiveDirectoryRoleBasedAccessControl:
          - azureRbacEnabled: true 
            managed: true
          defaultNodePool:
            - name: default
              vnetSubnetIdSelector:
                matchLabels:
                  meta.upbound.io/type: azure-virtual-subnet
                  meta.upbound.io/subnet-for: akscluster-nodes
              vmSize: Standard_B4ms
              nodeCount: 1
              enableAutoScaling: true
              minCount: 1
              maxCount: 3
              maxPods: 90
              osDiskSizeGb: 100
              osSku: Mariner
          networkProfile:
          - serviceCidr: 100.64.0.0/16
            dnsServiceIp: "100.64.0.10"
            podCidr: 100.99.0.0/16
            dockerBridgeCidr: 172.17.0.1/16
            loadBalancerSku: standard
            networkPlugin: azure
            networkPluginMode: Overlay
            ebpfDataPlane: cilium
          serviceMeshProfile:
          - mode: Istio
          workloadAutoscalerProfile:
          - kedaEnabled: true
          identity:
          - type: SystemAssigned
          resourceGroupNameSelector:
            matchLabels:
              meta.upbound.io/rg-name: crossplane-demo-rg
              meta.upbound.io/type: azure-resource-group
        writeConnectionSecretToRef:
          namespace: upbound-system
    patches:
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.id
      toFieldPath: status.aksId
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.name
      toFieldPath: spec.writeConnectionSecretToRef.name
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.kubernetesVersion
      toFieldPath: spec.forProvider.kubernetesVersion
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.location
      toFieldPath: spec.forProvider.location
      transforms:
        - type: map
          map:
            southcentralus: South Central US
            northcentralus: North Central US
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.name
      toFieldPath: spec.forProvider.dnsPrefix
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.name
      toFieldPath: spec.forProvider.dnsPrefix
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.nodeCount
      toFieldPath: spec.forProvider.defaultNodePool.nodeCount
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.authorizedIpRanges
      toFieldPath: spec.forProvider.apiServerAccessProfile.authorizedIpRanges
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.parameters.name
        - fromFieldPath: spec.parameters.location
        strategy: string
        string:
          fmt: "%s_%s_nodes_rg"
      toFieldPath: spec.forProvider.nodeResourceGroup
      policy:
        fromFieldPath: Required
