---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xaksclusters.containers.bjdazure.tech
spec:
  group: containers.bjdazure.tech
  names:
    kind: XAKSCluster
    plural: xaksclusters
  claimNames:
    kind: AKSCluster
    plural: aksclusters
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  nodeCount:
                    type: integer
                  name:
                    type: string
                  location:
                    type: string
                    enum:
                    - southcentralus
                    - northcentralus
                  clusterConfigurationUri:
                    type: string
                  clusterCommonConfigruationPath:
                    type: string
                  clusterAppsConfigruationPath:
                    type: string
                required:
                - nodeCount
                - name
                - location
                - clusterConfigurationUri
                - clusterCommonConfigruationPath
                - clusterAppsConfigruationPath
            required:
            - parameters
          status:
            type: object
            properties:
              aksId:
                description: The AKS Resource Id
                type: string